git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: diff-so-fancy
gui:
  theme:
    # Border color of focused window
    activeBorderColor:
      - "#a6e3a1" # green
      - bold

    # Border color of non-focused windows
    inactiveBorderColor:
      - "#f5e0dc" # rosewater

    # Border color of focused window when searching in that window
    searchingActiveBorderColor:
      - "#94e2d5" # teal
      - bold

    # Color of keybindings help text in the bottom line
    optionsTextColor:
      - "#a6e3a1" # green

    # Background color of selected line.
    # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
    selectedLineBgColor:
      - "#313244" # surface0

    # Background color of selected line when view doesn't have focus.
    inactiveViewSelectedLineBgColor:
      - bold

    # Foreground color of copied commit
    cherryPickedCommitFgColor:
      - "11111b" # crust

    # Background color of copied commit
    cherryPickedCommitBgColor:
      - "#f5e0dc" # rosewater

    # Foreground color of marked base commit (for rebase)
    markedBaseCommitFgColor:
      - "11111b" # crust

    # Background color of marked base commit (for rebase)
    markedBaseCommitBgColor:
      - "#f5e0dc" # rosewater

    # Color for file with unstaged changes
    unstagedChangesColor:
      - "#f38ba8" # red

    # Default text color
    defaultFgColor:
      - "#f5e0dc" # rosewater

  authorColors:
    "rajdeepsh": "#a6e3a1" # green
    "*": "#f38ba8" # red

  showCommandLog: false
  showBottomLine: false
  nerdFontsVersion: "3"
  showFileIcons: true
  commitHashLength: 0
  commitAuthorShortLength: 0
  scrollHeight: 8
  spinner:
    frames:
      - "[#     ]"
      - "[##    ]"
      - "[###   ]"
      - "[####  ]"
      - "[##### ]"
      - "[ #####]"
      - "[  ####]"
      - "[   ###]"
      - "[    ##]"
      - "[     #]"
      - "[    ##]"
      - "[   ###]"
      - "[  ####]"
      - "[ #####]"
      - "[##### ]"
      - "[####  ]"
      - "[###   ]"
      - "[##    ]"
    rate: 50